---
abstract: 'Minimalistic JSON. No dependencies.'
author:
  - 'David Oswald <davido [at] cpan [d.o.t] org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-Tiny
no_index:
  directory:
    - t
    - inc
provides:
  JSON::Tiny:
    file: lib/JSON/Tiny.pm
    version: 0.41
requires:
  perl: 5.008000
resources:
  repository: https://github.com/daoswald/JSON-Tiny.git
version: 0.41
