---
abstract: 'Minimalistic JSON. No dependencies.'
author:
  - 'David Oswald <davido[at]cpan[dot]org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-Tiny
no_index:
  directory:
    - t
    - inc
provides:
  JSON::Tiny:
    file: lib/JSON/Tiny.pm
    version: '0.54'
requires:
  perl: '5.008000'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/daoswald/JSON-Tiny.git
version: '0.54'
